"""empty message

Revision ID: 09931f79231a
Revises: 
Create Date: 2020-02-05 17:14:13.006314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09931f79231a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partname', sa.String(length=60), nullable=True),
    sa.Column('fcd', sa.Integer(), nullable=True),
    sa.Column('usd', sa.Integer(), nullable=True),
    sa.Column('sar', sa.Integer(), nullable=True),
    sa.Column('rub', sa.Integer(), nullable=True),
    sa.Column('yen', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_partname'), 'participants', ['partname'], unique=True)
    op.create_table('storages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storown', sa.String(length=60), nullable=True),
    sa.Column('stornum', sa.Integer(), nullable=True),
    sa.Column('current_capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storages_storown'), 'storages', ['storown'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('storid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['storid'], ['storages.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_storages_storown'), table_name='storages')
    op.drop_table('storages')
    op.drop_index(op.f('ix_participants_partname'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
